default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: account_manager_development
  host: <%= Rails.application.credentials.dig(:development, :db_host) %>
  username: <%= Rails.application.credentials.dig(:development, :db_username) %>
  password: <%= Rails.application.credentials.dig(:development, :db_password) %>

test:
  <<: *default
  database: account_manager_test
  host: <%= Rails.application.credentials.dig(:test, :db_host) %>
  username: <%= Rails.application.credentials.dig(:test, :db_username) %>
  password: <%= Rails.application.credentials.dig(:test, :db_password) %>

production:
  <<: *default
  database: account_manager_production
  host: <%= Rails.application.credentials.dig(:production, :db_host) %>
  username: <%= Rails.application.credentials.dig(:production, :db_username) %>
  password: <%= Rails.application.credentials.dig(:production, :db_password) %>

